name: adya_mahakaali_sadhana
description: A sacred chanting app for Bhairav Sadhana

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/batuk.mp3
    - assets/audio/swarna.mp3
    - assets/audio/skanda.mp3
    - assets/audio/maha.mp3
    - assets/images/batuk.jpg
    - assets/images/swarna.jpg
    - assets/images/skanda.jpg
    - assets/images/maha.jpg
